### ISSUE TITLE
Crashes after a short period of time

### ISSUE THREAD

**Issue by 04fsnape** [ChrisKnott/Eel#54]
Sorry for all the issues but I'm just trying to get a simple GUI up and running but I'm having quite a lot of problems.

My current GUI consists of 3 .html documents and 4 .css files (one global and three individual).

When I open my GUI it works fine at the start, I can click on each item of my menu and it switches between the html documents great. However, if I start clicking on the links in fairly quick succession the program crashes with no error in the console, but the error on the GUI is 
> localhost refused to connect

Even if I don't click very fast, the python script will end, but I can still click around for a while (it's very slow), I presume this is because it's cached or something, and then it will run into the same error as before.

Has anyone else experienced issues like this? My code is not very complicated.

Here is my python:

```
import eel
eel.init('web')
eel.start('settings.html', size=(1216, 736))
```

And my HTML on all 3 is literally just a menu with links at the moment and the CSS is just simple styling.

EDIT: I have no such problems if I go to localhost in my browser.

**Comment by ChrisKnott** [comment]
No need to apologize, thanks for raising issues rather than just moving on.

I will try and recreate your problems tomorrow (England are playing this evening!). You don't look like you are doing anything wrong. I think the best bet will be to add a debug mode with more logging, that should help work out what's happening.

**Comment by 04fsnape** [comment]
@ChrisKnott I'm wondering if perhaps it is a problem with Chrome Canary as my app seems to run in that my default, not sure how to make it run in normal chrome.

**Comment by 04fsnape** [comment]
After uninstalling Canary, the problem still persists. The window size now also needs to be increased further for some strange reason... I have scrollbars again (bear in mind this is still an issue from the previous issue, it should be 1200x700 but it seems to be an arbitrary number above each)...

**Comment by 04fsnape** [comment]
1216x736 are now the magic numbers...

**Comment by ChrisKnott** [comment]
@04fsnape Can you upload your project somewhere so I can try and recreate the issue?

**Comment by 04fsnape** [comment]
@ChrisKnott Sure, take a look at https://github.com/04fsnape/eel_test. If you open it and then just click between the pages via the menu on the left a bit you should see it crash.

**Comment by ChrisKnott** [comment]
@04fsnape I think the issue was that it was occasionally taking longer than 1 second to re-establish the websocket for the new page. The default behaviour when a websocket closes is wait 1 second, then see if there are any websockets open, and if there aren't, exit the Python process.

In the latest version, this can be overridden by providing a callback function to `init()`.

Here's an example which doesn't crash for me...
```
import eel

def on_close(page, sockets):
	print(page, 'closed')
	print('Still have sockets open to', sockets)

web_options = {
	"mode": "chrome-app",
	"host": "localhost",
	"port": 8000,
}
eel.init('web')
eel.start('settings.html', size=(1216, 739), options=web_options, callback=on_close)
```

Unfortunately this version also doesn't _quit_. It's up to you to come up with new logic for when you want to quit. One option would be to set a variable `changing_page` to true when the user clicks a button, wait till that call completes, then change the page. In the quit callback, only exit the Python process if `changing_page` is `False`.

Looking at your app though (which looks great!), it might be better to just keep a single page open the whole time, with a single websocket, and use AJAX to dynamically change the contents of the right hand side.

**Comment by 04fsnape** [comment]
@ChrisKnott 

I see. Thank you for putting the time in to have a look at the problem. 

Do you know if it's possible to tie the function to the close button on the title bar? Because if that is possible then it would work fine as far as I can tell.

If not then I think you're right, AJAX sounds like a good solution.

**Comment by ChrisKnott** [comment]
Currently there's not an easy way to do that. I will add some logic to track the actual processes as well later this week which will make this possible

**Comment by PolyviosP** [comment]
i have problem with ERR_CONNECTION_REFUSED i have trying every example but none of them work 
here is my code 

`import eel
 web_options = {"host": "127.0.0.1", 'port': 8000}

 eel.init(web)
 eel.start('lindex.html', size=(1100, 650), options = web_options, suppress_error=True)
`

**Comment by ilkerx** [comment]
The same here

**Comment by munabedan** [comment]
I found that my app was crashing while moving from one page to another, including the eel library to each page seemed to fix the problem:

``` html
<script type="text/javascript" src="/eel.js"></script>
```

I then navigate with:
``` javascript
    window.location.href="newpage.html"
```

Hope this works for you too

**Comment by ilkerx** [comment]
My problem is not while navigating to another page (maybe a sort of). When Chrome DevTools is open, i do Shift + F5 (without changing the main resources, just to refresh) it crashes. This suituation is happening randomly. Sometimes it crashes and sometimes (even after i repetadely Shift + F5) it doesn't.

I'm creating an important application with this and i'm afraid. I need urgent help.

**Comment by NarutoOp** [comment]
@munabedan Mun
Thanks this solved my problem.
I also included eel library to each pages and boom it started working smoothly without crashes.

**Comment by ilkerx** [comment]
My problem remains with this situation: I have my main html code in "web" folder and i'm changing contents of <body> tag with remote ajax. Adding some external javascript files (from web) dynamically. 

It doesn't crash all the time, crashes randomly when i press SHIFT + F5.
