### ISSUE TITLE
Prevent window resizing

### ISSUE THREAD

**Issue by 04fsnape** [ChrisKnott/Eel#55]
As you can probably tell, I would really like to try and use eel to make a professional GUI that is semi-indistinguishable from something built with tkinter and suchlike. To do this I think that it is critical that I have the ability to lock the window size. This is possible with some horrible JavaScript that just brings the window size back to the original size if you try and change it:

```
var size = [1216,739];
$(window).resize(function(){
  window.resizeTo(size[0], size[1]);
});
```
Although, this is far from ideal.

I tried to save you the work here by looking it up myself, but even after studying the eel source code I'm not too clear as to what's going on so I'm struggling to search for a solution in the correct context. The closest I came was something like [this](https://stackoverflow.com/questions/15030797/how-to-prevent-resizing-a-chrome-packaged-app).

If it's not already a chrome flag, perhaps this could be something that you could add to eel?

Thanks.

**Comment by ChrisKnott** [comment]
After a bit of research, this doesn't seem possible unfortunately. Modern browsers don't allow to block resizing as it's considered anti-user. I think that the only way to have this much control is to use Electron as the browser rather than Chrome.

I have tested using Electron and will make a new Issue with instructions now
