### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by whittyusername621** [ChrisKnott/Eel#93]
Hello all! Just started out playing around with this whole Eel thing. Looks fun! But I'm definitely doing something wrong.

Heres my structure:
app ->
- server.py
- another_module.py
- /web -> main.html

Heres my server.py

import eel
eel.init('web')
eel.start('main.html')

And when I go to launch it......

<img width="1440" alt="screen shot 2018-12-31 at 9 02 25 pm" src="https://user-images.githubusercontent.com/46291243/50570420-734c6d00-0d3f-11e9-90d1-8ea70fef7832.png">

While I'm here. Every time I launch the module it creates a new chrome icon in the dock. As you can see in the screen shot, there are four chrome apps in the dock.

**Comment by samuelhwilliams** [comment]
I'm not sure specifically what file structure you have, but I suspect it's the latter of these two examples:

<img width="363" alt="screen shot 2019-01-01 at 10 46 21" src="https://user-images.githubusercontent.com/2920760/50572201-8a787280-0db2-11e9-8b29-fef44c076735.png">
<img width="352" alt="screen shot 2019-01-01 at 10 46 40" src="https://user-images.githubusercontent.com/2920760/50572202-8a787280-0db2-11e9-9f9f-8c513dbcd1a4.png">

In the first case, I ran the server from the same directory (i.e. `python server.py`) and everything worked fine. In the second case, I ran the server from the parent directory (i.e. `python app/server.py`) and got the same 404 as you.

If this accurately describes your folder structure, then the quickest workaround is to do `eel.init("app/web")` instead (or something fancier using `__file__`), because `eel.init` takes a path is relative to the current working directory (where you're running the `python` command), not relative to the python entry file.

If this doesn't help you, maybe share your code/file structure and I'll take another look.

**Comment by whittyusername621** [comment]
Actually, I was able to solve the first problem. It was late and I'd had a beer, so I couldn't really tell you what I did to fix it.

The second issue is still bugging me though. Basically, every time I run the script after the first I get an 'os error 48: port is already in use'. Best I can tell- when the window gets closed or navigated away from, the python process (the server???) is still running.

As such, when I try to run it again, chrome or else the os kicks a subroutine into action to avoid the issue, creating an additional chrome icon in the dock. I'm guessing it's basically setting up a second environment.

I'm going to try setting an onclose event of some kind to trigger a quit event on the python side.

I'm... not great with this web stuff. I mean, the HTML/CSS is easy enough but I loath javascript- and anything to do with client to server just mystifies me.

**Comment by ChrisKnott** [comment]
By default the Python process (server) will continue running until the Chrome window is closed, then it should quit. Relevant code is here - https://github.com/ChrisKnott/Eel/blob/master/eel/__init__.py#L264

**Comment by whittyusername621** [comment]
Odd then that I'm getting this issue. Do you have any thoughts as to why chrome is opening a second/third/nth window?

**Comment by ChrisKnott** [comment]
It is normal to open a new chrome window every time you run the script. Sometimes I forget to include `eel.js` in main.html (in script tag). If you don't include that, then it doesn't have any way of knowing when the window closes.
